package model;
// Generated Sep 22, 2019 4:29:47 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Applog generated by hbm2java
 */
@Entity
@Table(name = "applog")
public class Applog implements java.io.Serializable {

	private Integer lid;
	private String ltime;
	private String luri;
	private String lmethod;
	private String lheader;

	public Applog() {
	}

	public Applog(String ltime, String luri, String lmethod, String lheader) {
		this.ltime = ltime;
		this.luri = luri;
		this.lmethod = lmethod;
		this.lheader = lheader;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lid", unique = true, nullable = false)
	public Integer getLid() {
		return this.lid;
	}

	public void setLid(Integer lid) {
		this.lid = lid;
	}

	@Column(name = "ltime", nullable = false)
	public String getLtime() {
		return this.ltime;
	}

	public void setLtime(String ltime) {
		this.ltime = ltime;
	}

	@Column(name = "luri", nullable = false)
	public String getLuri() {
		return this.luri;
	}

	public void setLuri(String luri) {
		this.luri = luri;
	}

	@Column(name = "lmethod", nullable = false)
	public String getLmethod() {
		return this.lmethod;
	}

	public void setLmethod(String lmethod) {
		this.lmethod = lmethod;
	}

	@Column(name = "lheader", nullable = false)
	public String getLheader() {
		return this.lheader;
	}

	public void setLheader(String lheader) {
		this.lheader = lheader;
	}

}
