package model;
// Generated Sep 22, 2019 4:29:47 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "subscriber")
public class Subscriber implements java.io.Serializable {

	private Integer id;
	private String name;
	private String msisdn;

	public Subscriber() {
	}

	public Subscriber(String name, String msisdn) {
		this.name = name;
		this.msisdn = msisdn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "msisdn", nullable = false)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

}
